// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var ReactDom                = require("react-dom");
var ReasonReact             = require("reason-react/src/ReasonReact.js");
var App$ServerRendering     = require("./app.bs.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function hydrateToElementWithId(reactElement, id) {
  var match = document.getElementById(id);
  if (match == null) {
    throw [
          Caml_builtin_exceptions.invalid_argument,
          "ReactDOMRE.renderToElementWithId : no element of id " + (id + " found in the HTML.")
        ];
  } else {
    ReactDom.hydrate(reactElement, match);
    return /* () */0;
  }
}

hydrateToElementWithId(ReasonReact.element(/* None */0, /* None */0, App$ServerRendering.make(/* array */[])), "react-root");

console.log("hello browser");

exports.hydrateToElementWithId = hydrateToElementWithId;
/*  Not a pure module */
