// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe          = require("reason-react/src/ReactDOMRe.js");
var ReasonReact         = require("reason-react/src/ReasonReact.js");
var App$ServerRendering = require("./app.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, App$ServerRendering.make(/* array */[])), "react-root");

console.log("hello browser");

/*  Not a pure module */
