// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function make(content, title, _) {
  return "\n  <!DOCTYPE html>\n    <html>\n      <head>\n        <title>" + (String(title) + ("</title>\n      </head>\n      <body>\n        <div id=\"react-root\">" + (String(content) + "</div>\n        <script src=\"/assets/bundle.js\"></script>\n      </body>\n    </html>\n")));
}

exports.make = make;
/* No side effect */
